# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b91c739ed6bfd407a05d72498d1c22ea03628d7cca6d719975ba9447ac827ff4d9537858e0906f30681ece08422b0dbf5dc5cd6bc5584dc2a4150c7c4e006bc2

test:
  secret_key_base: 9a6e8bb2dee1c6ffd5f12509795028f9afb3fb7d2377d4ab6b2f48cbbe57dcb68cb73aa7083beb56fc3112cf104cfa1184efe0553ee192f58021e3c771cf7222

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
